blank_issues_enabled: false
contact_links:
  - name: ğŸ—£ Ask a Question, get help
    url: https://github.com/gr2m/sandbox/discussions
    about: ğŸ¤” How does X work? Something is not right? Got an idea? Start here!
